pipeline:
  build:
    image: golang:latest
    commands:
      - go build -o segfautils
  dockerize:
    image: plugins/docker 
      settings:
        username:
          from_secret: username
        password:
          from_secret: password
        repo: projectsegfault/segfautils
        tags: latest
        dockerfile: Dockerfile

    
  
