pipeline:
  build:
    when:
      event: [push, pull_request, tag, deployment]
    image: golang:latest
    commands:
      - go build -o segfautils
  dockerize_n_publish:
    when:
      event: [push, tag, deployment]
    name: dockerize and publish
    image: plugins/docker 
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      repo: projectsegfault/segfautils
      tags: latest
      dockerfile: Dockerfile

    
  
